# Use the (faster) container-based infrastructure, see also
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: go
go:
  - 1.8

env:
  global:
  # GITHUB_USER
  - secure: "C88RAjHfbNjL0OIG/21fQ0HfgfCQZs2Jiqrw06ZtSsl9TdHcFhA7BnrbQnA7t9RI1rUy58QIZkqJInOZ7XzunQKnStmrQUASng++Sd22hPs01W8Djf9+f5kohQD7GV8eDHX35k9dWX37u4DBggtrIwwRa3kqqirUMocDCiWyH7ZplU6lUtLC4YhYwm030morde0+BDap+C9jBMKCdY00SryJkEMeMtXo0CZUoHdv2m8onWdhMs9Zl/uW0U57E6ttSrZzc9K19juEk8r/X+jCSOJ5blczWFkeLRZxUXIQhxsV8Ckx+Mod1yr8o/6xBcSV5xMHhDd55gaKKrrJzkFnqgTJhwSCssCSMYBGqkR9gRHekUogJmEHKIjmI75Pz6Ry+PBEIo7tSL21bYlfs3cIByT4Tpz8Cb8ZcJPBGfr5Qn2AtDgGUPusyOUDcaDZHL0NA3YQ5Lf0DWjimwF7vOv8BcW/6kxDzz+lk685gc9DQtf5X6ttoqr5hFiQ0r0/foTQo6qLFgeFHfBS1gay0gRoxqIJEJZ5FkJdQMJLY6t8zdpEbtBkiUmgWAxqHcAntgWfRZnzsyAfRFcUZX6m6p9yXecbu452inwVOHN/ioU6Gjf8omBbMOLVkNJoV66RXjrtVqp4T5/A+dr0KSxXjJ+xrfxxQ/yJyKAsDWJTQin9obs="
  # GITHUB_AUTH_TOKEN
  - secure: "CBgwbxfYz/4fhNd1B4W4Xz0sdSbpYgLIXJNNn+YzGouwrjsHGaiA3Ac/y9DsqPGQ6OqDJZJHZlVpOCNuDfEZWDdwiXoSCl8sNiNBiMSkKJfp3P0IHjLb9eCdqLFRTcQdUjzmbRUQhzngCSfKOaEEpEORUmwbomNZLtnjgiF0Jl5urucxyeO3WUN0dbDSkrdYYQbpHYXeKL33Aeqg6CHDRdzZIJrCsNkdChszGI/FX1v32Q1uu9xDbytO0HUyMJtqwUR/r3cdX3nVoFiJoehiky4IBvcvoLeDZCG+gzgNFkCkLTHc2Sqe+iMxqplDpf4hpXanVjFNj33OrrlJ5fMFqxpGrvWWFTIW8FVt5olG3IIjOJCDpMs7O/I79Y/yTESpZqkZl8h9WfdpDLyHp2bnzQI7UsCsURb1I+T58aKyRdix2Oe30VkHBXQKP3GjTpum6B/lg4bFBPnNgoZQ9xYDIEic+IVo1wvF3LbpaEFhxP60UIk8zWx0BZssdO9CaspLKBS6sSM90ibQPaxW9QAAvoHxfVn8iDCmSRanhAoFVAbBJn6gMaRoiUhJsQpSc32XfsqqxPAy43BesrSfVwyf4iwI4odY/vx1GL4h09c9+E6Vr320c0kgUIzR1ipuwBxBnXFamrMVH7Jrl7NSmqxxgyFhlAiQOqVzjs6/ctjDZfE="
  # BOOTERY_URL
  - secure: "N4sQC91qWHAU4ahpX8qZXNjqwWTxS6mHvUliSW0KMn0QyvfSQmRZEZiIItWD/irFnUlaqWewGb2DYy63jCgbQ4rX6yTl3WnUzw56rBs+YpTUgFtG0j4xfPTKdtCxTljgv8knEPR2tvjCwhqh6KL5W5yomKBD0SIJAiOWHQw3DWRVixrc4bp0pDR5x0Sl+5hherOdHLUxh/8Wc52TBN5MX/ngU1c0n7hrsOXmJGcyOEhbfEKG8Ve93iUAVHk8ZOe1x8BmAB9K7zyynVhy9q42fbWj2SyxNEgAxQs53i+E2kMYTiH/EciScHy9qbpS7SdbEEfr1VqAGtglHgR7Fav+uD1v56VY1R4YgOEk+9VPL48SJk3l3N6AFWkEpZAajipvq5U79z8hAVZY8DUzoFrTAT1govYsZzPe8yN7lO+WIPPejzHiduQeafbw4VW3DCl7KCUzFgg1izCnEA4+vROL3DGkSRDIsdrTYY3SJoIPM88cCfKbL96F01Z2ai0JeeAZ2UvNAGqSDsxt2cEImOGI8muACmV/MU8AgeO+m+0+DJwF/2L3snZ7VWavzzomwhO3Nze02gypEa7eBR744AjURAtGMV5gKg8IroCdtTV/TPOr/RjUyvX255Jvf1ugxscpDg/UQBEZSvAnNtaBDGoR9tvftP5xiwsCkFg/r3obaVA="

script:
  # Check whether files are syntactically correct.
  - "gofmt -l $(find . -name '*.go' | tr '\\n' ' ') >/dev/null"
  # Check whether files were not gofmt'ed.
  - gosrc=$(find . -name '*.go' | tr '\\n' ' '); [ $(gofmt -l $gosrc 2>&- | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $gosrc 2>&-; false)
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || go get -u github.com/gokrazy/autoupdate/cmd/... github.com/gokrazy/tools/cmd/gokr-packer'
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || gokr-boot -require_label=please-boot -set_label=please-merge -bootery_url=$BOOTERY_URL || travis_terminate $?'
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || { gokr-merge -require_label=please-merge; ret=$?; if [ $ret -eq 0 ]; then travis_terminate 0; elif [ $ret -eq 1 ]; then travis_terminate 1; else true; fi; }'
  # Update firmware files
  - go install ./cmd/gokr-update-firmware
  - gokr-update-firmware
  # update pull request
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || (go get -u github.com/gokrazy/autoupdate/cmd/gokr-amend && gokr-amend -set_label=please-boot *.bin *.elf *.dat)'
