name: Update kernel ref

on:
  schedule:
    # daily, hour and minute chosen arbitrarily
    - cron:  '8 3 * * *'

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        # Run on the latest minor release of Go 1.18:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: Get dependencies
      run: |
        GOPROXY=direct go get -u github.com/gokrazy/autoupdate/cmd/gokr-pull-firmware

    - name: Update firmware reference if newer firmware is available
      env:
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GH_USER: ${{ secrets.GH_USER }}
        GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
      run: |
        gokr-pull-firmware
